# Generated by Django 5.1.2 on 2024-11-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_postname_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.CharField(default='', max_length=254, unique=True),
        ),
        migrations.AlterModelTable(
            name='post',
            table='board',
        ),
    ]
