# Generated by Django 5.1.2 on 2024-11-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_post_email_alter_post_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='email',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
