# Generated by Django 5.1.2 on 2024-11-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_post_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='delete',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='contents',
            field=models.TextField(max_length=254),
        ),
        migrations.AlterField(
            model_name='post',
            name='email',
            field=models.CharField(max_length=254),
        ),
    ]
