# Generated by Django 5.1.2 on 2024-11-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_post_delete_alter_post_contents_alter_post_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
