# Generated by Django 5.1.2 on 2024-11-27 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_post_created_at_post_imgfile_post_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='imgfile',
            new_name='img_url',
        ),
    ]
