# Generated by Django 5.1.2 on 2024-11-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_rename_imgfile_post_img_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_num', models.IntegerField(default=0)),
                ('comment', models.TextField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=254)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'board_comment',
            },
        ),
    ]
