# Generated by Django 5.1.2 on 2024-11-28 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_post_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='delete',
            new_name='del_post',
        ),
    ]
