# Generated by Django 5.1.2 on 2024-11-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_rename_delete_post_del_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='del_post',
            field=models.IntegerField(default=0),
        ),
    ]
