# Generated by Django 5.1.2 on 2024-11-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_alter_post_del_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='del_post',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
